-- CreateTable
CREATE TABLE "public"."financingForm" (
    "id" SERIAL NOT NULL,
    "salutation" TEXT,
    "gender" TEXT,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "maritalStatus" TEXT NOT NULL,
    "birthDate" TIMESTAMP(3) NOT NULL,
    "sin" TEXT,
    "currentAddress" TEXT NOT NULL,
    "currentCity" TEXT NOT NULL,
    "currentProvince" TEXT NOT NULL,
    "currentPostalCode" TEXT NOT NULL,
    "currentDurationYear" INTEGER NOT NULL,
    "currentDurationMonth" INTEGER NOT NULL,
    "homeStatus" TEXT NOT NULL,
    "monthlyPayment" DOUBLE PRECISION,
    "prevAddress" TEXT,
    "prevCity" TEXT,
    "prevProvince" TEXT,
    "prevPostalCode" TEXT,
    "prevDurationYear" INTEGER,
    "prevDurationMonth" INTEGER,
    "employmentType" TEXT NOT NULL,
    "employer" TEXT NOT NULL,
    "occupation" TEXT NOT NULL,
    "employmentAddress" TEXT NOT NULL,
    "employmentCity" TEXT NOT NULL,
    "employmentProvince" TEXT NOT NULL,
    "employmentPostalCode" TEXT NOT NULL,
    "employmentPhone" TEXT,
    "employmentDurationYear" INTEGER NOT NULL,
    "employmentDurationMonth" INTEGER NOT NULL,
    "grossIncome" DOUBLE PRECISION NOT NULL,
    "prevEmployer" TEXT,
    "prevEmploymentPhone" TEXT,
    "prevEmploymentDurationYear" INTEGER,
    "prevEmploymentDurationMonth" INTEGER,
    "bankruptcy" TEXT,
    "repossession" TEXT,
    "coSignerAvailable" TEXT,
    "creditRating" TEXT,
    "lead_status" "public"."leadStatus" NOT NULL DEFAULT 'NEW',
    "vehicleId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "financingForm_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "public"."financingForm" ADD CONSTRAINT "financingForm_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES "public"."Vehicle"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
